name: CI

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src || true
    - name: Run tests
      run: |
        pip install pytest
        pytest -q
    - name: Execute EDA notebook (smoke)
      run: |
        pip install nbformat nbconvert
        jupyter nbconvert --execute notebooks/eda_overview.ipynb --to html --ExecutePreprocessor.timeout=600
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eda-report
        path: reports/
